{% set name = "anywidget" %}
{% set version = "0.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anywidget-{{ version }}.tar.gz
  sha256: 58dded8e86ec27ce28760c9457317663113d9af608947ee6a8d0ecb528b22cdc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - hatch-jupyter-builder
    - jupyterlab
    - pip
  run:
    - python >=3.7
    - ipywidgets
    - typing_extensions
    - psygnal
    - watchfiles

test:
  imports:
    - anywidget
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/anywidget/
  summary: simple, custom Jupyter widgets
  description: |
    anywidget is a new Python library that greatly simplifies creating and publishing 
    custom Jupyter Widgets. Unlike the traditional (cookiecutter) approach, with 
    anywidget you 1) avoid fiddling with build steps and bundlers, 2) can prototype 
    widgets from within a notebook, and 3) get a modern front-end developer experience. 
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/manzt/anywidget

extra:
  recipe-maintainers:
    - manzt
    - giswqs
